# Build
root:              _gh_pages
dest:              <%= site.root %>

# Less.js metadata
current_version:   <%= less.version %>

# Site metadata
brand:             lesscss.org
title:             Less.js
lead:              LESS « The Dynamic Stylesheet Language
description: >
  LESS extends CSS with dynamic behavior such as variables, mixins, operations and functions.
  LESS runs on both the server-side (with Node.js and Rhino) or client-side (modern browsers only).

# Documentation License
license:
  type:            <%= pkg.licenses[0].type %>
  url:             <%= pkg.licenses[0].url %>

# URLs
repo:              <%= pkg.homepages %>
issues:            <%= pkg.homepages %>/issues?&state=open
download:
  source:          <%= pkg.homepages %>/archive/master.zip
  latest:          https://raw.github.com/less/less.js/master/dist/less-<%= less.version %>.min.js

cdn:
  cloudflare:      //cdnjs.cloudflare.com/ajax/libs/less.js/1.5.0/less.min.js

# SEO/SEM
analytics:
  alexa:           lpTeh1awA400OE
  google:          false
  google_site_id:  false