# =============================================
# BUILD CONFIG
# =============================================

root:             _gh_pages
dest:             <%= site.root %>
assets:           <%= site.dest %>/assets
date:             <%= new Date() %>


# Data
data:             data

# Templates
templates:        templates
pages:            <%= site.templates %>
includes:         <%= site.templates %>/includes
layouts:          <%= site.templates %>/layouts
layoutext:        .hbs
layout:           default

# Styles
styles:           styles
components:       <%= site.styles %>/components


# =============================================
# EXTENSIONS
# =============================================

helpers:          <%= site.templates %>/helpers
plugins:
  # - assemble-contrib-permalinks
  # - assemble-contrib-anchors
  # - assemble-contrib-toc


# =============================================
# PROJECT METADATA
# =============================================

# Site metadata
brand:             lesscss.org
title:             Less.js
lead:              LESS « The Dynamic Stylesheet Language
description: >
  LESS extends CSS with dynamic behavior such as variables, mixins, operations and functions.
  LESS runs on both the server-side (with Node.js and Rhino) or client-side (modern browsers only).

# URLs
homepage:          http://lesscss.org
repo:              <%= pkg.repository.url %>
issues:            <%= pkg.bugs.url %>?&state=open

# Download links
download:
  source:          <%= pkg.homepages %>/archive/master.zip
  latest:          https://raw.github.com/less/less.js/master/dist/less-<%= less.version %>.min.js


# =============================================
# SEO/SEM
# =============================================

analytics:
  alexa:           lpTeh1awA400OE
  google:
    id:             UA-XXXXXXXX-YY
    domain:         lesscss.org
    siteid:
    tags:           FOO-012345 # Google Tags (see: https://www.google.com/tagmanager/)


# =============================================
# SOCIAL / SHARING
# =============================================

# Comments
disqus:
  enabled:        false
  shortname:      <%= pkg.name %>

# Social
social:
  twitter:
    via:          false
    username:     false
  facebook:       false
  linkedin:       false
  gplus:          false
  hn:             false
  google:         false

# Sharing
sharing:
  twitter:        false
  facebook:       false
  gplus:          false
  hn:             false
  google:         false
